import turtle
turtle.pendown()
turtle.pensize(7)
turtle.pencolor('dark blue')
#нижнее основание
turtle.forward(50)
turtle.left(110)
turtle.pencolor('light blue')
turtle.forward(150)
turtle.right(180)
turtle.forward(150)
turtle.left(70)
turtle.pencolor('dark blue')
turtle.forward(50)
turtle.left(90)
turtle.pencolor('light blue')
turtle.forward(141)
turtle.right(180)
turtle.forward(141)
turtle.left(90)
turtle.pencolor('dark blue')
turtle.forward(50)
turtle.left(70)
turtle.pencolor('light blue')
turtle.forward(150)
turtle.right(180)
turtle.forward(150)
turtle.left(110)
turtle.pencolor('dark blue')
turtle.forward(50)
turtle.left(70)
#правая сторона
turtle.forward(50)
turtle.left(110)
turtle.pencolor('light blue')
turtle.forward(235)
turtle.right(180)
turtle.forward(235)
turtle.left(70)
turtle.pencolor('dark blue')
turtle.forward(50)
turtle.left(110)
turtle.pencolor('light blue')
turtle.forward(270)
turtle.right(180)
turtle.forward(270)
turtle.left(70)
turtle.pencolor('dark blue')
turtle.forward(50)
turtle.left(110)
#верхнее основание
turtle.forward(310)
turtle.right(70)
#делаю ручки тележки
turtle.forward(30)
turtle.left(70)
turtle.forward(20)
#возвращаюсь обратно
turtle.left(180)
turtle.forward(20)
turtle.right(70)
#левая сторона
turtle.forward(150)
turtle.penup()
turtle.forward(30)
turtle.pendown()
turtle.forward(50)
turtle.left(70)
turtle.forward(175)
turtle.right(135)
turtle.penup()
turtle.forward(40)
turtle.pendown()
turtle.dot(30)
turtle.right(45)
turtle.penup()
turtle.forward(120)
turtle.pendown()
turtle.dot(30)

turtle.done()