import turtle
turtle.pendown()
turtle.pencolor('white')
turtle.left(90)
turtle.penup()
turtle.forward(150)
turtle.pendown()

turtle.begin_fill()
turtle.fillcolor('grey')
turtle.forward(150)
turtle.left(90)
turtle.circle(150, 15)
turtle.left(90)
turtle.forward(150)
turtle.end_fill()

turtle.right(180)
turtle.begin_fill()
turtle.fillcolor('light green')
turtle.forward(150)
turtle.left(90)
turtle.circle(150, 45)
turtle.left(90)
turtle.forward(150)
turtle.end_fill()

turtle.right(180)
turtle.begin_fill()
turtle.fillcolor('light yellow')
turtle.forward(150)
turtle.left(90)
turtle.circle(150, 75)
turtle.left(90)
turtle.forward(150)
turtle.end_fill()

turtle.right(180)
turtle.begin_fill()
turtle.fillcolor('pink')
turtle.forward(150)
turtle.left(90)
turtle.circle(150, 90)
turtle.left(90)
turtle.forward(150)
turtle.end_fill()

turtle.right(180)
turtle.begin_fill()
turtle.fillcolor('light blue')
turtle.forward(150)
turtle.left(90)
turtle.circle(150, 135)
turtle.left(90)
turtle.forward(150)
turtle.end_fill()
turtle.done()